// Generated by dts-bundle v0.7.3

declare module 'postmask' {
    import { Result } from 'postmask/Result';
    import { IOptions, IGlobalOptions } from 'postmask/options';
    import { IOptimizer, registerOptimizer } from 'postmask/single/optimizer';
    export { Result };
    export function optimizeAsync(source: string, path: string, options: IOptions): Promise<Result>;
    export function configurate(config: IGlobalOptions): void;
    export { IOptimizer, registerOptimizer };
}

declare module 'postmask/Result' {
    export class Report {
        errors: Message[];
        warnings: Message[];
        result: string;
    }
    export class Message {
        message: string;
        line?: number;
        col?: number;
        source?: string;
        level: 'error' | 'warning' | 'info';
        middleware?: string;
    }
    export class Result<T = string> {
        result: T;
        report: Report;
    }
}

declare module 'postmask/options' {
    export interface IOptions {
        minify?: boolean;
        base?: string;
        plugins?: string[];
        configs?: {
            [key: string]: any;
        };
        [key: string]: any;
    }
    export interface IGlobalOptions {
        mask?: any;
        io?: any;
        [key: string]: any;
    }
    export const Default: IOptions;
    export function prepare(options: any): IOptions;
}

declare module 'postmask/single/optimizer' {
    import { Report, Result } from 'postmask/Result';
    import { IOptions } from 'postmask/options';
    export interface IContext {
        report: Report;
    }
    export interface IOptimizer {
        (node: any, ctx: IContext, next: INext): any;
    }
    export interface INext {
        (node?: any): any;
    }
    export function optimizeAsync(source: string, path: string, options: IOptions): Promise<Result>;
    /**
      *
      * @param pattern eg. 'style';`*` ~ `*:before`, `*:after`
      * @param fn
      */
    export function registerOptimizer(pattern: string, fn: IOptimizer): void;
    export function getOptimizers(name: any): IOptimizer[];
}

